apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubediag-dashboard
  namespace: kubediag
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubediag-dashboard-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - triggers/status
  verbs:
  - get
  - patch
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubediag-dashboard-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubediag-dashboard-role
subjects:
- kind: ServiceAccount
  name: kubediag-dashboard
  namespace: kubediag
---
apiVersion: v1
kind: Service
metadata:
  name: kubediag-dashboard
  namespace: kubediag
spec:
  ports:
  - nodePort: 30055
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubediag-dashboard
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubediag-dashboard
  namespace: kubediag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubediag-dashboard
  template:
    metadata:
      labels:
        app: kubediag-dashboard
    spec:
      containers:
      - command:
        - /main
        image: hub.c.163.com/kubediag/kubediag-dashboard:v0.1.0
        name: dashboard
        resources:
          limits:
            cpu: 800m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 50Mi
      serviceAccountName: kubediag-dashboard
      terminationGracePeriodSeconds: 10
